enableAllRules = true

[rule.line-length-limit]
  arguments = [100]

[rule.add-constant]
  arguments = [{ maxLitCount = "1000", allowInts = "0,1,2" }]
  Exclude = ["TEST"]

[rule.exported]
  Disabled = true

[rule.package-comments]
  Disabled = true

[rule.unhandled-error]
  arguments = ["fmt.Print", "fmt.Fprint", "fmt.Fprintln", "fmt.Printf", "fmt.Println", "fmt.Fprintf"]
